module.exports = 
  INIT_GAME: \INIT_GAME
  START_GAME: \START_GAME

  BUTTON_CLICK: \BUTTON_CLICK
  REEL_RESIZE: \REEL_RESIZE

  RIGHT_BUTTON_CLICK: \RIGHT_BUTTON_CLICK
  LEFT_BUTTON_CLICK: \LEFT_BUTTON_CLICK